In [1]:
import pandas as pd

In [46]:
# Reading csv file
df = pd.read_csv('diamonds.csv')
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1.0,0.23,Ideal,E,SI2,61.5,55.0,326.0,3.95,3.98,2.43
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
3,3.0,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31
4,4.0,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
...,...,...,...,...,...,...,...,...,...,...,...
53936,53936.0,0.72,Ideal,D,SI1,60.8,57.0,2757.0,5.75,5.76,3.50
53937,53937.0,0.72,Good,D,SI1,63.1,55.0,2757.0,5.69,5.75,3.61
53938,53938.0,0.70,Very Good,D,SI1,62.8,60.0,2757.0,5.66,5.68,3.56
53939,53939.0,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.15,6.12,3.74
53940,53940.0,0.75,Ideal,D,SI2,62.2,55.0,2757.0,5.83,5.87,3.64

In [4]:
df[df['price']<400]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326.0,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
2,3,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
50612,50613,0.26,Very Good,H,VS1,62.0,56.0,399.0,4.08,4.11,2.54
50613,50614,0.25,Very Good,D,VS2,61.1,60.0,399.0,4.07,4.11,2.50
50614,50615,0.27,Very Good,G,VS1,58.8,57.0,399.0,4.25,4.36,2.53
50615,50616,0.24,Good,F,VS1,62.5,60.0,399.0,3.96,3.98,2.48
50616,50617,0.25,Good,D,VS1,57.6,60.0,399.0,4.15,4.18,2.40

In [20]:
# Prices less than 400 and cut is 'premium'

df[(df['price']<400) & (df['cut']=="Premium")]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
3,4,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
12,13,0.22,Premium,F,SI1,60.4,61.0,342.0,3.88,3.84,2.33
14,15,0.20,Premium,E,SI2,60.2,62.0,345.0,3.79,3.75,2.27
15,16,0.32,Premium,E,I1,60.9,58.0,345.0,4.38,4.42,2.68
26,27,0.24,Premium,I,VS1,62.5,57.0,355.0,3.97,3.94,2.47
28279,28280,0.31,Premium,J,SI1,60.9,60.0,363.0,4.36,4.38,2.66
28284,28285,0.32,Premium,J,SI1,62.2,59.0,365.0,4.37,4.41,2.73
31591,31592,0.20,Premium,E,VS2,59.8,62.0,367.0,3.79,3.77,2.26
31592,31593,0.20,Premium,E,VS2,59.0,60.0,367.0,3.81,3.78,2.24
31593,31594,0.20,Premium,E,VS2,61.1,59.0,367.0,3.81,3.78,2.32
31594,31595,0.20,Premium,E,VS2,59.7,62.0,367.0,3.84,3.80,2.28
31596,31597,0.20,Premium,F,VS2,62.6,59.0,367.0,3.73,3.71,2.33
31600,31601,0.20,Premium,D,VS2,62.3,60.0,367.0,3.73,3.68,2.31
31601,31602,0.20,Premium,D,VS2,61.7,60.0,367.0,3.77,3.72,2.31
31603,31604,0.30,Premium,J,VS2,62.2,58.0,368.0,4.28,4.30,2.67
31607,31608,0.30,Premium,J,VS2,60.6,59.0,368.0,4.34,4.38,2.64
31608,31609,0.30,Premium,H,SI2,60.9,59.0,368.0,4.32,4.35,2.64
34947,34948,0.30,Premium,H,SI2,61.9,60.0,378.0,4.27,4.29,2.65
38252,38253,0.31,Premium,J,VS2,62.5,60.0,380.0,4.31,4.36,2.71
38254,38255,0.31,Premium,J,VS2,62.4,60.0,380.0,4.29,4.33,2.69
38261,38262,0.26,Premium,H,VS1,62.3,59.0,382.0,4.06,4.10,2.54
38262,38263,0.26,Premium,G,VS1,61.3,60.0,382.0,4.07,4.12,2.51
38274,38275,0.21,Premium,E,VS2,60.5,59.0,386.0,3.87,3.83,2.33
38275,38276,0.21,Premium,E,VS2,59.6,56.0,386.0,3.93,3.89,2.33
38276,38277,0.21,Premium,D,VS2,61.6,59.0,386.0,3.82,3.78,2.34
38277,38278,0.21,Premium,D,VS2,60.6,60.0,386.0,3.85,3.81,2.32
38278,38279,0.21,Premium,D,VS2,59.1,62.0,386.0,3.89,3.86,2.29
38279,38280,0.21,Premium,D,VS2,58.3,59.0,386.0,3.96,3.93,2.30
41590,41591,0.31,Premium,H,SI2,59.5,59.0,390.0,4.39,4.45,2.63
41607,41608,0.32,Premium,J,VS2,61.9,58.0,393.0,4.35,4.38,2.70
41608,41609,0.32,Premium,J,VS2,61.9,59.0,393.0,4.35,4.38,2.70
43988,43989,0.31,Premium,F,I1,62.9,59.0,394.0,4.33,4.29,2.71
43989,43990,0.21,Premium,E,SI2,61.9,56.0,394.0,3.84,3.82,2.37
43991,43992,0.30,Premium,J,VS1,62.6,58.0,394.0,4.28,4.31,2.69
43998,43999,0.30,Premium,I,SI1,60.9,59.0,394.0,4.34,4.36,2.65
44004,44005,0.30,Premium,J,VS1,62.6,60.0,394.0,4.22,4.28,2.66
44009,44010,0.30,Premium,F,SI2,61.3,58.0,394.0,4.28,4.33,2.64
47284,47285,0.30,Premium,G,SI2,62.5,59.0,394.0,4.27,4.31,2.68
47292,47293,0.30,Premium,G,SI2,62.3,59.0,394.0,4.25,4.29,2.66
47293,47294,0.30,Premium,J,VS1,62.6,58.0,394.0,4.27,4.32,2.69
50611,50612,0.27,Premium,G,VS2,62.4,59.0,397.0,4.11,4.13,2.57

In [21]:
df[df.cut.isin(['Premium', 'Good'])]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
2,3,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75
10,11,0.30,Good,J,SI1,64.0,55.0,339.0,4.25,4.28,2.73
...,...,...,...,...,...,...,...,...,...,...,...
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756.0,5.79,5.74,3.49
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756.0,5.74,5.73,3.43
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757.0,5.69,5.73,3.58
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757.0,5.69,5.75,3.61
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.15,6.12,3.74

In [26]:
df[(df['cut']=='Premium') | (df['cut']=='Good')]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
2,3,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75
10,11,0.30,Good,J,SI1,64.0,55.0,339.0,4.25,4.28,2.73
...,...,...,...,...,...,...,...,...,...,...,...
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756.0,5.79,5.74,3.49
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756.0,5.74,5.73,3.43
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757.0,5.69,5.73,3.58
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757.0,5.69,5.75,3.61
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.15,6.12,3.74

In [27]:
df[df.clarity.str.startswith('S')]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326.0,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
4,5,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75
7,8,0.26,Very Good,H,SI1,61.9,55.0,337.0,4.07,4.11,2.53
10,11,0.30,Good,J,SI1,64.0,55.0,339.0,4.25,4.28,2.73
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757.0,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757.0,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757.0,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757.0,5.83,5.87,3.64

In [29]:
df[df.cut.str.contains('G')]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
2,3,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31
4,5,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336.0,3.94,3.96,2.48
6,7,NaN,Very Good,I,VVS1,62.3,57.0,336.0,3.95,3.98,2.47
7,8,0.26,Very Good,H,SI1,61.9,55.0,337.0,4.07,4.11,2.53
...,...,...,...,...,...,...,...,...,...,...,...
53927,53928,0.79,Good,F,SI1,58.1,59.0,2756.0,6.06,6.13,3.54
53932,53933,0.70,Very Good,E,VS2,60.5,59.0,2757.0,5.71,5.76,3.47
53933,53934,0.70,Very Good,E,VS2,61.2,59.0,2757.0,5.69,5.72,3.49
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757.0,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757.0,5.66,5.68,3.56

In [30]:
df[~df.cut.str.contains('G')]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326.0,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
3,4,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
8,9,0.22,Fair,E,VS2,65.1,61.0,337.0,3.87,3.78,2.49
11,12,0.23,Ideal,J,VS1,62.8,56.0,340.0,3.93,3.90,2.46
...,...,...,...,...,...,...,...,...,...,...,...
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756.0,5.74,5.73,3.43
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757.0,5.69,5.73,3.58
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757.0,5.75,5.76,3.50
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757.0,5.83,5.87,3.64

In [35]:
df.query('price < 400 and cut == "Premium"')

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
3,4,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
12,13,0.22,Premium,F,SI1,60.4,61.0,342.0,3.88,3.84,2.33
14,15,0.20,Premium,E,SI2,60.2,62.0,345.0,3.79,3.75,2.27
15,16,0.32,Premium,E,I1,60.9,58.0,345.0,4.38,4.42,2.68
26,27,0.24,Premium,I,VS1,62.5,57.0,355.0,3.97,3.94,2.47
28279,28280,0.31,Premium,J,SI1,60.9,60.0,363.0,4.36,4.38,2.66
28284,28285,0.32,Premium,J,SI1,62.2,59.0,365.0,4.37,4.41,2.73
31591,31592,0.20,Premium,E,VS2,59.8,62.0,367.0,3.79,3.77,2.26
31592,31593,0.20,Premium,E,VS2,59.0,60.0,367.0,3.81,3.78,2.24
31593,31594,0.20,Premium,E,VS2,61.1,59.0,367.0,3.81,3.78,2.32
31594,31595,0.20,Premium,E,VS2,59.7,62.0,367.0,3.84,3.80,2.28
31596,31597,0.20,Premium,F,VS2,62.6,59.0,367.0,3.73,3.71,2.33
31600,31601,0.20,Premium,D,VS2,62.3,60.0,367.0,3.73,3.68,2.31
31601,31602,0.20,Premium,D,VS2,61.7,60.0,367.0,3.77,3.72,2.31
31603,31604,0.30,Premium,J,VS2,62.2,58.0,368.0,4.28,4.30,2.67
31607,31608,0.30,Premium,J,VS2,60.6,59.0,368.0,4.34,4.38,2.64
31608,31609,0.30,Premium,H,SI2,60.9,59.0,368.0,4.32,4.35,2.64
34947,34948,0.30,Premium,H,SI2,61.9,60.0,378.0,4.27,4.29,2.65
38252,38253,0.31,Premium,J,VS2,62.5,60.0,380.0,4.31,4.36,2.71
38254,38255,0.31,Premium,J,VS2,62.4,60.0,380.0,4.29,4.33,2.69
38261,38262,0.26,Premium,H,VS1,62.3,59.0,382.0,4.06,4.10,2.54
38262,38263,0.26,Premium,G,VS1,61.3,60.0,382.0,4.07,4.12,2.51
38274,38275,0.21,Premium,E,VS2,60.5,59.0,386.0,3.87,3.83,2.33
38275,38276,0.21,Premium,E,VS2,59.6,56.0,386.0,3.93,3.89,2.33
38276,38277,0.21,Premium,D,VS2,61.6,59.0,386.0,3.82,3.78,2.34
38277,38278,0.21,Premium,D,VS2,60.6,60.0,386.0,3.85,3.81,2.32
38278,38279,0.21,Premium,D,VS2,59.1,62.0,386.0,3.89,3.86,2.29
38279,38280,0.21,Premium,D,VS2,58.3,59.0,386.0,3.96,3.93,2.30
41590,41591,0.31,Premium,H,SI2,59.5,59.0,390.0,4.39,4.45,2.63
41607,41608,0.32,Premium,J,VS2,61.9,58.0,393.0,4.35,4.38,2.70
41608,41609,0.32,Premium,J,VS2,61.9,59.0,393.0,4.35,4.38,2.70
43988,43989,0.31,Premium,F,I1,62.9,59.0,394.0,4.33,4.29,2.71
43989,43990,0.21,Premium,E,SI2,61.9,56.0,394.0,3.84,3.82,2.37
43991,43992,0.30,Premium,J,VS1,62.6,58.0,394.0,4.28,4.31,2.69
43998,43999,0.30,Premium,I,SI1,60.9,59.0,394.0,4.34,4.36,2.65
44004,44005,0.30,Premium,J,VS1,62.6,60.0,394.0,4.22,4.28,2.66
44009,44010,0.30,Premium,F,SI2,61.3,58.0,394.0,4.28,4.33,2.64
47284,47285,0.30,Premium,G,SI2,62.5,59.0,394.0,4.27,4.31,2.68
47292,47293,0.30,Premium,G,SI2,62.3,59.0,394.0,4.25,4.29,2.66
47293,47294,0.30,Premium,J,VS1,62.6,58.0,394.0,4.27,4.32,2.69
50611,50612,0.27,Premium,G,VS2,62.4,59.0,397.0,4.11,4.13,2.57

In [33]:
df[df.cut.str.contains('P')]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
3,4,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
12,13,0.22,Premium,F,SI1,60.4,61.0,342.0,3.88,3.84,2.33
14,15,0.20,Premium,E,SI2,60.2,62.0,345.0,3.79,3.75,2.27
15,16,0.32,Premium,E,I1,60.9,58.0,345.0,4.38,4.42,2.68
...,...,...,...,...,...,...,...,...,...,...,...
53928,53929,0.79,Premium,E,SI2,61.4,58.0,2756.0,6.03,5.96,3.68
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756.0,5.79,5.74,3.49
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756.0,5.74,5.73,3.43
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757.0,5.69,5.73,3.58
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.15,6.12,3.74

In [36]:
df[df['cut']>'P']

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
3,4,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336.0,3.94,3.96,2.48
6,7,NaN,Very Good,I,VVS1,62.3,57.0,336.0,3.95,3.98,2.47
7,8,0.26,Very Good,H,SI1,61.9,55.0,337.0,4.07,4.11,2.53
...,...,...,...,...,...,...,...,...,...,...,...
53932,53933,0.70,Very Good,E,VS2,60.5,59.0,2757.0,5.71,5.76,3.47
53933,53934,0.70,Very Good,E,VS2,61.2,59.0,2757.0,5.69,5.72,3.49
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757.0,5.69,5.73,3.58
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757.0,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.15,6.12,3.74

In [34]:
df[df.cut.str.startswith('P')]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
3,4,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63
12,13,0.22,Premium,F,SI1,60.4,61.0,342.0,3.88,3.84,2.33
14,15,0.20,Premium,E,SI2,60.2,62.0,345.0,3.79,3.75,2.27
15,16,0.32,Premium,E,I1,60.9,58.0,345.0,4.38,4.42,2.68
...,...,...,...,...,...,...,...,...,...,...,...
53928,53929,0.79,Premium,E,SI2,61.4,58.0,2756.0,6.03,5.96,3.68
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756.0,5.79,5.74,3.49
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756.0,5.74,5.73,3.43
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757.0,5.69,5.73,3.58
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.15,6.12,3.74

In [38]:
df.nlargest(3, 'price')

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
27749,27750,2.29,Premium,I,VS2,60.8,60.0,18823.0,8.50,8.47,5.16
27748,27749,2.00,Very Good,G,SI1,63.5,56.0,18818.0,7.90,7.97,5.04
27747,27748,1.51,Ideal,G,IF,61.7,55.0,18806.0,7.37,7.41,4.56

In [39]:
df.nsmallest(3, 'price')

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326.0,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
2,3,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31

In [44]:
# print all rows where any of the column value is None.
df[df.isnull().any(axis=1)]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
1,2,0.21,Premium,E,SI1,59.8,61.0,326.0,NaN,NaN,NaN
6,7,NaN,Very Good,I,VVS1,62.3,57.0,336.0,3.95,3.98,2.47
18,19,0.30,Good,J,SI1,63.8,56.0,NaN,4.23,4.26,2.71
23,24,0.31,Very Good,J,SI1,NaN,62.0,353.0,4.39,4.43,2.62

In [47]:
# print all rows where all columns values are None
df[df.isnull().all(axis=1)]

   Unnamed: 0  carat  cut color clarity  depth  table  price   x   y   z
1         NaN    NaN  NaN   NaN     NaN    NaN    NaN    NaN NaN NaN NaN